# Generated by Django 6.0.3 on 2026-04-01 03:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name'], 'verbose_name': 'Contato', 'verbose_name_plural': 'Contatos'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['company_name', 'name'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cpf__isnull', False), ('customer_type', 'PF'), ('name__isnull', False)), models.Q(('cnpj__isnull', False), ('company_name__isnull', False), ('customer_type', 'PJ')), _connector='OR'), name='check_customer_type'),
        ),
    ]
